### ISSUE TITLE
Update window.System to window.Nebula in docs for script tag usage, window.System is no longer defined

### ISSUE THREAD

**Issue by geonom** [creativelifeform/three-nebula#103]
Hey there,

trying to use the script tag as per the documentation at the bottom of the main github page of three-nebula (see minimum working example below), but it leads to this error:

Firefox: "Uncaught TypeError: window.System is undefined"
Edge: "Uncaught TypeError: Cannot destructure property 'System' of 'window.System' as it is undefined."

This is the example code I am testing:

```
<html>
<head><title>Test</title></head>
<body>
    <script type='text/javascript' src="js/three.js"></script>
    <script type='text/javascript' src='js/three-nebula.js'></script>
    <script>
        const { System, Emitter, Rate, Span } = window.System;
        const system = new System();
    </script>
</body>
```

I am a hobby programmer, so there is probably something obvious I am missing - however, I cant find it.

The three.js implementation works without issues, the script files are definitely accessible.

Any help would be appreciated :)

**Comment by geonom** [comment]
Tried to create a fiddle, in case that helps.

https://jsfiddle.net/o7htcgwa/

**Comment by rohan-deshpande** [comment]
Hey thanks I am checking it out

**Comment by rohan-deshpande** [comment]
Okay I think I might have broken this functionality with some webpack config I needed to implement to get the library working in node environments. I'm looking into it.

**Comment by rohan-deshpande** [comment]
Ah okay so there's two problems here. The first is my fault - the global variable is no longer called `System` it's `Nebula` so I need to update the docs for this. The second is that you are trying to access the code via https://raw.githubusercontent.com/creativelifeform/three-nebula/master/build/three-nebula.js and you can't do this - github is not a CDN. So you can fix your fiddle if you use the following code 

```html
<html>
<head><title>Test</title></head>
<body>
    <script type='text/javascript' src="three.js"></script>
    <script type='text/javascript' src='https://unpkg.com/three-nebula@5.1.1/build/three-nebula.js'></script>
    <script>
        const { System, Emitter, Rate, Span } = window.Nebula;
        const system = new System();
    </script>
</body>
```
