### ISSUE TITLE
fromJSONAsync while adding three-nebula as a script tag 

### ISSUE THREAD

**Issue by ironwolf-interactive** [creativelifeform/three-nebula#124]
More a question than an Issue. How can I use fromJSONAsync in pure JS while three-nebula is added with HTML script tag?
I tried few different approach but everything fails:

**1.**
```javascript
new System.fromJSONAsync(...
```
→ `Uncaught ReferenceError: System is not defined`

**2.**
```javascript
new Nebula.fromJSONAsync(...
``` 
→ `Uncaught TypeError: Nebula.fromJSONAsync is not a constructor`

**3.**
```javascript
system = new Nebula.default();
system.fromJSONAsync(...
```
→ `Uncaught TypeError: system.fromJSONAsync is not a function`

**4.**
```javascript
const { System, Emitter, Rate, Span } = window.Nebula;
const system = new System();
system.fromJSONAsync(...
```
→ `Uncaught TypeError: system.fromJSONAsync is not a function`

.
Other functions works fine. I can create emitter with particles through code and it works perfectly.

BTW. this library is really awesome :)

**Comment by rohan-deshpande** [comment]
Hi, thanks!

So I can help you out better, can you please create a [codesandbox](https://codesandbox.io) so I can get a look at how you're setting things up?

**Comment by ironwolf-interactive** [comment]
https://codesandbox.io/s/static-nebula-fromjson-5nyuz
Lack of everything but should be enough to show the problem. 
As you can see getCount() work but fromJSONAsync() "is not a function" :(

Thanks for help :)

**Comment by rohan-deshpande** [comment]
Hmm not sure what is going on there but you can see an example of it working here https://codesandbox.io/s/three-nebula-quickstart-script-tag-mnz9b

**Comment by ironwolf-interactive** [comment]
Thanks 👍 

**This solves the problem:**
```javascript
const { System: Nebula, SpriteRenderer } = window.Nebula;
```

There is just misinformation in the Readme ;)

**Comment by rohan-deshpande** [comment]
Ah! Yep okay I changed the name of the export and forgot to update the docs! thanks! I think someone else raised this before and I forgot about it. I'll fix it now.
