### ISSUE TITLE
System is not emitting particles

### ISSUE THREAD

**Issue by neoshamangames** [creativelifeform/three-nebula#191]
Hello,

I am new to this project. Apologies if this belongs in Discussions. I am hoping to get help figuring out why my set up is not working.  I am integrating three-nebula in to a larger project.  I installed it via npm.

I used the example code to get started with some modifications to make it compile (some imports were missing).  I do not see any particles though the rest of my scene renders.  I use a WebGLRenderer.  Here is the relevant code:

```
        const system = new System();
        const emitter = new Emitter();
        const renderer = new SpriteRenderer(scene, THREE);

        // Set emitter rate (particles per second) as well as the particle initializers and behaviours
        emitter
            .setRate(new Rate(new Span(4, 16), new Span(0.01)))
            .setInitializers([
                new Position(new PointZone(0, 0)),
                new Mass(1),
                new Radius(6, 12),
                new Life(30),
                new RadialVelocity(45, new Vector3D(0, 1, 0), 180),
            ])
            .setBehaviours([
                new Alpha(1, 0),
                new Scale(0.1, 1.3),
                new Color(new THREE.Color(), new THREE.Color()),
            ]);

        // add the emitter and a renderer to your particle system
        system
            .addEmitter(emitter)
            .addRenderer(renderer)
            .emit({  });

        //for later reference
        this.system = system;
        this.emitter = emitter;
```

I am unclear if this alone should start the Emitter. I guess not since I am passing an empty object to system.emit()  I added this function which executes on a keypress:

```
        this.emitter.emit();
        console.log("particle system", this.system);
        console.log("particle emitter", this.emitter);
```

Here is what I see outputted to the console:
![three-nebula-console](https://user-images.githubusercontent.com/3624969/146272468-d20565d8-4768-44bb-8c0f-bd8c6ce274e7.JPG)

As you can see, there are no particles in the emitter and it's age is 0.  I assume this is why I see nothing. Please advice.

**Comment by rohan-deshpande** [comment]
Hi, it will be much easier to help if you set up a https://codesandbox.io with your code in it, then I can easily see what the problem is.

**Comment by neoshamangames** [comment]
These examples seem to be completely different in structure than what is presented in the readme.  I see they use the class "Nebula" instead of "System".  Is the readme out of date? Is this the suggestion way to go? I will try following these examples to see if that works better in my project.

**Comment by neoshamangames** [comment]
Turns out my problem was I needed to call system.update() in my animation loop.  I suggest the readme be updated to make this clear.

**Comment by rohan-deshpande** [comment]
Yeah README is a bit out of date, will update it soon. Thanks for that I will include that in the docs for sure. Glad you sorted it.
