### ISSUE TITLE
The requested module './node_modules/three-nebula/build/three-nebula.js' does not provide an export named 'Alpha'

### ISSUE THREAD

**Issue by samyH** [creativelifeform/three-nebula#211]
Following your usage via module:

`import System, {
        Emitter,
        Rate,
        Span,
        Position,
        Mass,
        Radius,
        Life,
        Velocity,
        PointZone,
        Vector3D,
        Alpha,
        Scale,
        Color,
    } from './node_modules/three-nebula/build/three-nebula.js';
    import * as THREE from './node_modules/three/build/three.module.js';`

Produces the error:
The requested module './node_modules/three-nebula/build/three-nebula.js' does not provide an export named 'Alpha'

Any help is apprciated.

Cheers

**Comment by rohan-deshpande** [comment]
There's a test covering this behaviour so if you could provide a codesandbox.io example to show the problem I'd appreciate it.
