### ISSUE TITLE
Editor App crash with Apple Silicon

### ISSUE THREAD

**Issue by williammanco** [creativelifeform/three-nebula#218]
Hi @rohan-deshpande, the editor and library are really nice and useful.
Probably the app does not support M1 processors, the app is not stable and the viewer crashes.

I couldn't find the source of the editor to contribute, it's probably not open source, but I was wondering if it could be released. 

It would be nice to make the editor usable from the browser afterwards.

Thank you in advance for your reply
W

**Comment by rohan-deshpande** [comment]
Hi there, sorry the Nebula desktop app is not open source. It is built using [NWJS](https://github.com/nwjs/nw.js/issues/7620) which currently has M1 support in the backlog. You could try using [Rosetta](https://support.apple.com/en-us/HT211861).

I am considering porting the editor to the web, but this will means I will incur maintenance costs for what will essentially become a cloud based app, so I am not keen on that just now. Maybe in the future.
