### ISSUE TITLE
Nebula.Color: Passing 0 as a color value causes a crash.

### ISSUE THREAD

**Issue by davidpox** [creativelifeform/three-nebula#51]
Version: 4.0.1.

Adding a Color behaviour to an emitter with `0` or `0x0` as a colour causes it to crash:
`TypeError: Cannot read property 'getValue' of null`.
0x000001 works.

Reason: 
In `src/math/ColorSpan.js` Line 60 - you check if you have a colours object. 0 will return false therefore returning null.

**Comment by manthrax** [comment]
PR #85

**Comment by rohan-deshpande** [comment]
Hmm just noting that `ColorSpan` takes either the string `'random'` or an array as its constructor arg. Since `createColorSpan` is basically just a factory for creating color spans, I think you'd need to pass `'0'` or `'0x0'`, I haven't tried it though.

**Comment by rohan-deshpande** [comment]
Resolved by https://github.com/creativelifeform/three-nebula/pull/85
