### ISSUE TITLE
Single emitter with multiple textures?

### ISSUE THREAD

**Issue by davidpox** [creativelifeform/three-nebula#58]
Is there a way for a emitter to pick between two or more THREE.Sprites randomly?

**Comment by rohan-deshpande** [comment]
Currently this is not supported. Could be a pretty cool feature though! 

I’d probably want some level of control over the randomisation, maybe it just cycles through the textures at a set interval by default and then there’s an option to completely randomise which texture to render?

**Comment by rohan-deshpande** [comment]
Hmmm you know what, you might be able to achieve this with the `Body` initialiser. If you pass an array of sprites for the first argument. If may work. Let me know how it goes!

**Comment by MasatoMakino** [comment]
@rohan-deshpande 

`Body` initialiser and array of sprites, it works fine.

Version : 
"three": "0.106.2",
"three-nebula": "5.0.0-alpha",

Demo : 
https://masatomakino.github.io/threejs-lab/nebulaFire.html

Excerpted code
```js
const loader = new TextureLoader();
const sprites = urlArray.map(url => {
  return new Sprite(
    new SpriteMaterial({
      map: loader.load(url),
      blending: AdditiveBlending
    })
  );
});
this._body = new Body(sprites);
```

thanks.
