### ISSUE TITLE
GPURenderer depth sorting is broken

### ISSUE THREAD

**Issue by rohan-deshpande** [creativelifeform/three-nebula#90]
Reported by @davidpox here https://github.com/creativelifeform/three-nebula/issues/65#issuecomment-590254221 there are currently depth sorting issues with the `GPURenderer`, need to investigate possible solutions

**Comment by rohan-deshpande** [comment]
@davidpox would it be possible for you to create a [codesandbox](https://codesandbox.io/) to set something up I could use as a sandbox for testing this out? You can use my [quickstart](https://codesandbox.io/s/three-nebula-quickstart-kz6uv) sandbox to make the setup a bit easier.

**Comment by rohan-deshpande** [comment]
@davidpox I have played around a bit in a branch you can see here #92. In this branch, I've set up a new sandbox (which you can run via `npm run sandbox`) called `gpu-renderer-depth-sorting`. Here I set up a simple test case of rendering a box mesh with a particle system. Using the `SpriteRenderer` the scene looks like this:

![Screen Shot 2020-03-29 at 11 39 33 am](https://user-images.githubusercontent.com/1079637/77837198-22316000-71b2-11ea-8afa-aee05f4aa151.png)

The current implementation, the one you are using, the scene looks like this:

![Screen Shot 2020-03-29 at 11 40 56 am](https://user-images.githubusercontent.com/1079637/77837235-8eac5f00-71b2-11ea-9b9a-4b148931118e.png)

At the moment I'm a bit surprised at how easy the solution has been. I've simply changed the `ShaderMaterial` props to 

```
  depthTest: true,
  depthWrite: false,
```

Here is the result 

![Screen Shot 2020-03-29 at 11 44 36 am](https://user-images.githubusercontent.com/1079637/77837257-cf0bdd00-71b2-11ea-837f-47cbe643ddc1.png)

So I think this might help.

**Comment by rohan-deshpande** [comment]
@davidpox This has now been merged, you should be able to try it out in `develop` just like you were before. Please let me know how it goes.

**Comment by davidpox** [comment]
Thanks, currently on other projects but will test this Friday the latest!

**Comment by davidpox** [comment]
Can confirm this issue has been fixed! Thank you so much!
![3aK9PDxF](https://user-images.githubusercontent.com/7888472/78345012-1ddfbb00-7595-11ea-9741-1352f0dc040c.png)

**Comment by rohan-deshpande** [comment]
Resolved by #92
