### ISSUE TITLE
Request : Please make the Behaviour class public

### ISSUE THREAD

**Issue by MasatoMakino** [creativelifeform/three-nebula#98]
## Current behavior

The [Behaviour class](https://creativelifeform.github.io/three-nebula/api/class/src/behaviour/Behaviour.js~Behaviour.html) is not accessible from the public. And the Behaviour class cannot be extended.

## Expected behavior

The Behaviour class is accessible from the public.

## Motivation / Use Case

Third party developers will be able to create custom behaviors.

## Background

Currently, the [Color behavior](https://creativelifeform.github.io/three-nebula/api/class/src/behaviour/Color.js~Color.html) in three-nebula has two variables, ColorA and ColorB.

I want to set the transparency to a more granular level. For this reason, I have prototyped a custom behavior with the color of the Canvas element as a variable.

https://github.com/MasatoMakino/three-nebula-behaviour-plugin
https://masatomakino.github.io/three-nebula-behaviour-plugin/demo/

This is a color behavior with canvas elements and png images as variables.

This prototype works in 5.1.0 and does not work in 5.1.1.

## Why it doesn't work

This prototype is a custom class that extends the Behavior class in the src directory.

From [this commit](https://github.com/creativelifeform/three-nebula/commit/4efc53a081732efcfde7d4cdf0cd0b322c379bea), the src folder has been removed from the npm package.
That's why I can't extend the Behavior class from `src/behaviour/Behaviour.js`.

## Additional information

If [getEasingByName()](https://creativelifeform.github.io/three-nebula/api/function/index.html#static-function-getEasingByName) and [SUPPORTED_JSON_BEHAVIOUR_TYPES](https://creativelifeform.github.io/three-nebula/api/variable/index.html#static-variable-SUPPORTED_JSON_BEHAVIOUR_TYPES) are public, third party developers can customize the ``fromJson()`` function.

However, the public SUPPORTED_JSON_BEHAVIOUR_TYPES has a Side effects. If the behavior has a duplicate ``TYPE``, fromJson will not work. You can't limit what ``TYPE`` to third party developers. 

I've thought of several ideas. They are not the best, but I hope they will help you. 

1. keep SUPPORTED_JSON_BEHAVIOUR_TYPES private.
2. make the function for registering TYPE.

## Environment

macOS 10.15.2
three-nebula 5.1.0 - 5.1.1
webpack 4.43.0

Thank you.

**Comment by rohan-deshpande** [comment]
Hey thanks for the detailed issue. Yes I removed the `src` directory from the npm package as it shouldn't really be there. However your request to make `Behaviour` public is totally reasonable. I have a very large release/update coming soon so I will bundle it in there.

**Comment by cjsjy123** [comment]
when it will be released, I can’t wait to use it ☺  @rohan-deshpande

**Comment by rohan-deshpande** [comment]
Really soon please wait a little longer!

**Comment by cjsjy123** [comment]
> Really soon please wait a little longer!

will include editor?

**Comment by rohan-deshpande** [comment]
@cjsjy123 yes, the editor is what is holding up the release a bit, I want the editor to be available at this time. I've made the change and committed it to the develop branch in #100 please wait a tiny bit longer, it'll be out in master soon!

**Comment by cjsjy123** [comment]
> @cjsjy123 yes, the editor is what is holding up the release a bit, I want the editor to be available at this time. I've made the change and committed it to the develop branch in #100 please wait a tiny bit longer, it'll be out in master soon!

COOL!!!
